import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { I18nProvider } from "../i18n";
import { SETTING_HELP_LINKS, SettingHelp } from "./SettingHelp";

describe("SettingHelp", () => {
  it("renders only allowlisted official links with safe external-link attributes", () => {
    const html = renderToStaticMarkup(<SettingHelp id="openai-help" text="OpenAI help" href={SETTING_HELP_LINKS.openaiApiKeys} />);

    expect(html).toContain("https://platform.openai.com/api-keys");
    expect(html).toContain('target="_blank"');
    expect(html).toContain('rel="noopener noreferrer"');
  });

  it("localizes helper copy", () => {
    const html = renderToStaticMarkup(<I18nProvider initialLocale="zh-CN"><SettingHelp id="token-help" text="This token is generated by ConsistenCy, not an external API provider." /></I18nProvider>);

    expect(html).toContain("由 ConsistenCy 自行生成");
  });
});
