import type { ReviewFinding, ReviewReport } from "@consistency/schema";

function location(finding: ReviewFinding): string {
  if (finding.startLine === undefined) return finding.file;
  return finding.startLine === finding.endLine
    ? `${finding.file}:${finding.startLine}`
    : `${finding.file}:${finding.startLine}-${finding.endLine}`;
}

function findingMarkdown(finding: ReviewFinding): string {
  return [
    `### [${finding.severity.toUpperCase()}] ${finding.title}`,
    `**${finding.severity.toUpperCase()} · ${finding.confidence} · \`${location(finding)}\`**`,
    "",
    `**Evidence:** ${finding.evidence}`,
    "",
    `**Recommendation:** ${finding.recommendation}`
  ].join("\n");
}

export function renderReviewComment(report: ReviewReport, options: {
  webBaseUrl?: string;
  providerName: string;
  maxFindings?: number;
}): string {
  const topFindings = report.findings.slice(0, options.maxFindings ?? 8);
  const agentSummary = report.agentRuns
    .map(run => `- **${run.agentName}:** ${run.status}, ${run.findings.length} finding(s)`)
    .join("\n");
  const reportUrl = options.webBaseUrl
    ? `${options.webBaseUrl.replace(/\/$/, "")}/?view=report&job=${encodeURIComponent(report.jobId)}`
    : undefined;
  const mode = options.providerName === "mock"
    ? "> **Demo mode:** This review used the deterministic MockLLM provider."
    : `> Model provider: **${options.providerName}**`;

  return [
    "# ConsistenCy PR Review",
    "",
    mode,
    "",
    `**Score:** ${report.score}/100 · **Risk:** ${report.riskLevel.toUpperCase()} · **Findings:** ${report.findings.length}`,
    "",
    report.summary,
    "",
    "## Agent Summary",
    agentSummary || "- No agent runs recorded.",
    "",
    "## Top Findings",
    topFindings.length > 0 ? topFindings.map(findingMarkdown).join("\n\n") : "No findings were reported.",
    report.findings.length > topFindings.length
      ? `\n_${report.findings.length - topFindings.length} additional finding(s) are available in the full report._`
      : "",
    reportUrl ? `\n[View full report in ConsistenCy](${reportUrl})` : "",
    "",
    "---",
    "Generated by ConsistenCy multi-agent review."
  ].filter(Boolean).join("\n").slice(0, 60_000);
}
