import { riskBandForFindings, staticRiskDisplayLabel, tokenUsageNotesForAgentRuns, tokenUsageStatus, type ReviewFinding, type ReviewReport } from "@consistency/schema";
import { sanitizeExecutionError } from "../../security/redact";

function location(finding: ReviewFinding): string {
  if (finding.startLine === undefined) return finding.file;
  return finding.startLine === finding.endLine
    ? `${finding.file}:${finding.startLine}`
    : `${finding.file}:${finding.startLine}-${finding.endLine}`;
}

function findingMarkdown(finding: ReviewFinding): string {
  const meta: string[] = [
    finding.severity.toUpperCase(),
    finding.confidence,
    `\`${location(finding)}\``
  ];
  if (finding.score !== undefined) {
    meta.push(`Score: ${finding.score}/10`);
  }
  if (finding.alsoReportedBy && finding.alsoReportedBy.length > 0) {
    meta.push(`Also: ${finding.alsoReportedBy.join(", ")}`);
  }

  const lines = [
    `### [${finding.severity.toUpperCase()}] ${finding.title}`,
    `**${meta.join(" · ")}**`,
    "",
    `**Evidence:** ${finding.evidence}`,
  ];
  if (finding.trigger) {
    lines.push("", `**Trigger scenario:** ${finding.trigger}`);
  }
  lines.push("", `**Recommendation:** ${finding.recommendation}`);
  return lines.join("\n");
}

export function renderReviewComment(report: ReviewReport, options: {
  webBaseUrl?: string;
  providerName: string;
  maxFindings?: number;
}): string {
  const topFindings = report.findings.slice(0, options.maxFindings ?? 8);
  const agentSummary = report.agentRuns
    .map(run => {
      const status = run.agentName === "DeterministicAnalyzer" ? "reported" : tokenUsageStatus(run.tokenUsage);
      const usage = status === "unknown" ? ", token usage: unknown" : status === "partial" ? ", token usage: partial" : "";
      const reason = run.status === "failed" && run.error
        ? `; reason: ${sanitizeExecutionError(run.error).replace(/[\r\n]+/g, " ").replace(/[\\`*_<>]/g, "\\$&")}` : "";
      return `- **${run.agentName}:** ${run.status}, ${run.findings.length} finding(s)${usage}${reason}`;
    })
    .join("\n");
  const reportUrl = options.webBaseUrl
    ? `${options.webBaseUrl.replace(/\/$/, "")}/?view=report&job=${encodeURIComponent(report.jobId)}`
    : undefined;
  const mode = `> Model provider: **${options.providerName}**`;

  return [
    "# ConsistenCy PR Review",
    "",
    mode,
    "",
    `**Score:** ${report.score}/100 · **Static risk:** ${staticRiskDisplayLabel(report.riskLevel, report.staticRiskLabel)} · **Finding risk:** ${(report.riskBand ?? riskBandForFindings(report.findings)).toUpperCase()} · **Findings:** ${report.findings.length}`,
    report.duplicates && report.duplicates.length > 0
      ? `_${report.duplicates.length} duplicate finding(s) were merged deterministically; the finding count excludes merged duplicates._`
      : "",
    report.filteredFindingCount
      ? `_${report.filteredFindingCount} finding(s) were withheld after scoring (below the score floor or past the report caps); they are not shown._`
      : "",
    "",
    report.summary,
    "",
    "## Agent Summary",
    agentSummary || "- No agent runs recorded.",
    ...(report.tokenUsageNotes ?? tokenUsageNotesForAgentRuns(report.agentRuns)).map(note => `> ${note}`),
    "",
    "## Top Findings",
    topFindings.length > 0 ? topFindings.map(findingMarkdown).join("\n\n") : "No findings were reported.",
    report.findings.length > topFindings.length
      ? `\n_${report.findings.length - topFindings.length} additional finding(s) are available in the full report._`
      : "",
    reportUrl ? `\n[View full report in ConsistenCy](${reportUrl})` : "",
    report.preExistingIssues && report.preExistingIssues.length > 0
      ? [
          "",
          `<details>`,
          `<summary><b>Pre-existing issues (${report.preExistingIssues.length})</b></summary>`,
          "",
          ...report.preExistingIssues.map(f => `- **${f.severity.toUpperCase()}** \`${location(f)}\`: ${f.title}`),
          `</details>`
        ].join("\n")
      : "",
    "",
    "---",
    "Generated by ConsistenCy multi-agent review."
  ].filter(Boolean).join("\n").slice(0, 60_000);
}
