/**
 * Audit types — the shape of every event the Kernel records.
 *
 * All Kernel operations that have a security or observability consequence
 * produce an AuditEvent. The journal is append-only; no record can be mutated
 * or deleted after it is written.
 *
 * SECURITY NOTE: No AuditEvent must ever contain a raw CapabilityHandle.
 * Only the 12-hex-char `handleFingerprint` (from `auditFingerprint()`) is
 * permitted in the log. Callers must enforce this before calling `journal.record`.
 */

import type { PrincipalId } from "../identity/principal.js";
import type { ResourceKind } from "../identity/resource.js";
import type { DenyReason } from "../capability/errors.js";

// ---------------------------------------------------------------------------
// Union of all audit event types
// ---------------------------------------------------------------------------

export type AuditEvent =
  | CapabilityIssuedEvent
  | CapabilityRevokedEvent
  | SyscallAuthorisedEvent
  | CommitIntentAcceptedEvent
  | CommitIntentDeniedEvent;

// ---------------------------------------------------------------------------
// Base fields shared by all events
// ---------------------------------------------------------------------------

interface BaseAuditEvent {
  /** Unique event ID — generated by the journal implementation. */
  readonly id?: string;
  /** Unix timestamp (ms) when the event was recorded. */
  readonly timestamp: number;
}

// ---------------------------------------------------------------------------
// Specific event types
// ---------------------------------------------------------------------------

export interface CapabilityIssuedEvent extends BaseAuditEvent {
  readonly type: "capability.issued";
  readonly capabilityId: string;
  /** 12-character hex prefix of the handle — NOT the full handle. */
  readonly handleFingerprint: string;
  readonly subject: PrincipalId;
  readonly action: string;
  readonly resourceKind: ResourceKind;
  readonly expiresAt?: number;
}

export interface CapabilityRevokedEvent extends BaseAuditEvent {
  readonly type: "capability.revoked";
  readonly capabilityId: string;
  /** 12-character hex prefix of the handle. */
  readonly handleFingerprint: string;
  readonly subject: PrincipalId;
  readonly revokedBy: PrincipalId;
}

export interface SyscallAuthorisedEvent extends BaseAuditEvent {
  readonly type: "syscall.authorised";
  readonly principal: PrincipalId;
  /** 12-character hex prefix, or "(unknown)" when the handle was not found. */
  readonly handleFingerprint: string;
  readonly action: string;
  readonly resourceKind: ResourceKind;
  readonly decision: "allow" | "deny";
  readonly reason: DenyReason | "granted";
}

/**
 * A commit intent was accepted (authorised + handed to the durable sink).
 * Carries only the payload SHA-256 — never the payload body, handle, or
 * credential.
 */
export interface CommitIntentAcceptedEvent extends BaseAuditEvent {
  readonly type: "commit.intent_accepted";
  readonly intentId: string;
  readonly action: string;
  readonly resourceKind: ResourceKind;
  readonly subject: PrincipalId;
  readonly idempotencyKey: string;
  readonly payloadHash: string;
}

/**
 * A commit intent was rejected at authorisation. Records the deny reason
 * without the payload body, handle, or credential.
 */
export interface CommitIntentDeniedEvent extends BaseAuditEvent {
  readonly type: "commit.intent_denied";
  readonly action: string;
  readonly resourceKind: ResourceKind;
  readonly subject: PrincipalId;
  readonly idempotencyKey: string;
  readonly reason: string;
}
